# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0001_initial'),
        ('Park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.Car', verbose_name='Car')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Park.Park', verbose_name='Park')),
            ],
            options={
                'verbose_name': 'Rezervation',
                'verbose_name_plural': 'Rezervations',
            },
        ),
    ]
