# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-05-17 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0002_park_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='number_of_car_inside',
            field=models.PositiveSmallIntegerField(verbose_name='Number of Car'),
        ),
    ]
