# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-05-17 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0003_auto_20180517_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='number_of_car_inside',
        ),
    ]
