# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-05-23 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0004_remove_park_number_of_car_inside'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='number_of_car_inside',
            field=models.PositiveSmallIntegerField(default='20', verbose_name='Number of Car'),
        ),
    ]
