# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('type', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekdays+saturday', 'Weekdays + Saturday'), ('weekdays+weekend', 'Weekdays + Weekend')], default='weekdays', max_length=50, verbose_name='Days')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Park.Park', verbose_name='Park')),
            ],
            options={
                'verbose_name': 'WorkingHours',
                'verbose_name_plural': 'WorkingHours',
            },
        ),
    ]
